export const SET_UNIVERSE = 'SET_UNIVERSE';
export const SET_TOPIC = 'SET_TOPIC';

export const LOAD_UNIVERSE_REQUEST = 'LOAD_UNIVERSE_REQUEST';
export const LOAD_UNIVERSE_SUCCESS = 'LOAD_UNIVERSE_SUCCESS';
export const LOAD_UNIVERSE_FAILURE = 'LOAD_UNIVERSE_FAILURE';

export const LOAD_UNIVERSES_REQUEST = 'LOAD_UNIVERSES_REQUEST';
export const LOAD_UNIVERSES_SUCCESS = 'LOAD_UNIVERSES_SUCCESS';
export const LOAD_UNIVERSES_FAILURE = 'LOAD_UNIVERSES_FAILURE';

export const LOAD_CHAT_REQUEST = 'LOAD_CHAT_REQUEST';
export const LOAD_CHAT_SUCCESS = 'LOAD_CHAT_SUCCESS';
export const LOAD_CHAT_FAILURE = 'LOAD_CHAT_FAILURE';

export const LOAD_INVENTORY_REQUEST = 'LOAD_INVENTORY_REQUEST';
export const LOAD_INVENTORY_SUCCESS = 'LOAD_INVENTORY_SUCCESS';
export const LOAD_INVENTORY_FAILURE = 'LOAD_INVENTORY_FAILURE';

export const LOAD_TOPIC_BY_HANDLE_REQUEST = 'LOAD_TOPIC_BY_HANDLE_REQUEST';
export const LOAD_TOPIC_BY_HANDLE_SUCCESS = 'LOAD_TOPIC_BY_HANDLE_SUCCESS';
export const LOAD_TOPIC_BY_HANDLE_FAILURE = 'LOAD_TOPIC_BY_HANDLE_FAILURE';

export const LOAD_TOPIC_CONTENT_REQUEST = 'LOAD_TOPIC_CONTENT_REQUEST';
export const LOAD_TOPIC_CONTENT_SUCCESS = 'LOAD_TOPIC_CONTENT_SUCCESS';
export const LOAD_TOPIC_CONTENT_FAILURE = 'LOAD_TOPIC_CONTENT_FAILURE';