export const SET_UNIVERSE = 'SET_UNIVERSE';
export const SET_TOPIC = 'SET_TOPIC';

export const REQUEST_UNIVERSE = 'REQUEST_UNIVERSE';
export const SUCCESS_UNIVERSE = 'SUCCESS_UNIVERSE';
export const FAILURE_UNIVERSE = 'FAILURE_UNIVERSE';

export const REQUEST_UNIVERSES = 'REQUEST_UNIVERSES';
export const SUCCESS_UNIVERSES = 'SUCCESS_UNIVERSES';
export const FAILURE_UNIVERSES = 'FAILURE_UNIVERSES';

export const REQUEST_CHAT = 'REQUEST_CHAT';
export const SUCCESS_CHAT = 'SUCCESS_CHAT';
export const FAILURE_CHAT = 'FAILURE_CHAT';

export const REQUEST_INVENTORY = 'REQUEST_INVENTORY';
export const SUCCESS_INVENTORY = 'SUCCESS_INVENTORY';
export const FAILURE_INVENTORY = 'FAILURE_INVENTORY';

export const REQUEST_TOPIC_BY_HANDLE = 'REQUEST_TOPIC_BY_HANDLE';
export const SUCCESS_TOPIC_BY_HANDLE = 'SUCCESS_TOPIC_BY_HANDLE';
export const FAILURE_TOPIC_BY_HANDLE = 'FAILURE_TOPIC_BY_HANDLE';

export const REQUEST_TOPIC_CONTENT = 'REQUEST_TOPIC_CONTENT';
export const SUCCESS_TOPIC_CONTENT = 'SUCCESS_TOPIC_CONTENT';
export const FAILURE_TOPIC_CONTENT = 'FAILURE_TOPIC_CONTENT';