// export const SET_UNIVERSE = 'SET_UNIVERSE';
// export const SET_TOPIC    = 'SET_TOPIC';

export const REQUEST_READ_UNIVERSE = 'REQUEST_READ_UNIVERSE';
export const SUCCESS_READ_UNIVERSE = 'SUCCESS_READ_UNIVERSE';
export const FAILURE_READ_UNIVERSE = 'FAILURE_READ_UNIVERSE';

export const REQUEST_READ_UNIVERSES = 'REQUEST_READ_UNIVERSES';
export const SUCCESS_READ_UNIVERSES = 'SUCCESS_READ_UNIVERSES';
export const FAILURE_READ_UNIVERSES = 'FAILURE_READ_UNIVERSES';

export const REQUEST_READ_CHAT = 'REQUEST_READ_CHAT';
export const SUCCESS_READ_CHAT = 'SUCCESS_READ_CHAT';
export const FAILURE_READ_CHAT = 'FAILURE_READ_CHAT';

export const REQUEST_READ_INVENTORY = 'REQUEST_READ_INVENTORY';
export const SUCCESS_READ_INVENTORY = 'SUCCESS_READ_INVENTORY';
export const FAILURE_READ_INVENTORY = 'FAILURE_READ_INVENTORY';

export const REQUEST_READ_TOPIC = 'REQUEST_READ_TOPIC';
export const SUCCESS_READ_TOPIC = 'SUCCESS_READ_TOPIC';
export const FAILURE_READ_TOPIC = 'FAILURE_READ_TOPIC';

export const REQUEST_READ_TOPIC_CONTENT = 'REQUEST_READ_TOPIC_CONTENT';
export const SUCCESS_READ_TOPIC_CONTENT = 'SUCCESS_READ_TOPIC_CONTENT';
export const FAILURE_READ_TOPIC_CONTENT = 'FAILURE_READ_TOPIC_CONTENT';

export const REQUEST_CREATE_UNIVERSE = 'REQUEST_CREATE_UNIVERSE';
export const SUCCESS_CREATE_UNIVERSE = 'SUCCESS_CREATE_UNIVERSE';
export const FAILURE_CREATE_UNIVERSE = 'FAILURE_CREATE_UNIVERSE';

export const REQUEST_CREATE_TOPIC = 'REQUEST_CREATE_TOPIC';
export const SUCCESS_CREATE_TOPIC = 'SUCCESS_CREATE_TOPIC';
export const FAILURE_CREATE_TOPIC = 'FAILURE_CREATE_TOPIC';

export const REQUEST_CREATE_USER = 'REQUEST_CREATE_USER';
export const SUCCESS_CREATE_USER = 'SUCCESS_CREATE_USER';
export const FAILURE_CREATE_USER = 'FAILURE_CREATE_USER';

