#!/bin/bash



set -e

set -u



RUN_ON_MYDB="psql -d aquestdb -U aquestuser -h 130.211.68 --set ON_ERROR_STOP=on --set AUTOCOMMIT=off mydb"



$RUN_ON_MYDB <<SQL

drop schema if exists new_my_schema;

create table my_new_schema.my_new_table (like my_schema.my_table);

create table my_new_schema.my_new_table2 (like my_schema.my_table2);

commit;

SQL



$RUN_ON_MYDB <<SQL

create index my_new_table_id_idx on my_new_schema.my_new_table(id);

create index my_new_table2_id_idx on my_new_schema.my_new_table2(id);

commit;

SQL
