#!/bin/sh

# if `test -d ./dist/img`;
# then
#   `rm -r ./dist/img`;
#   `cp -r ./src/client/img ./dist/img`;
# else
#   `mkdir ./dist/img`;
#   `cp -r ./src/client/img ./dist/img`;
# fi
# cp ./src/client/img/* ./dist/img/

clear
nodemon -q -x "babel-node" --watch ./src/server -e js,html ./src/server/server.js
