#!/bin/sh

# if `test -d ./dist/img`;
# then
#   `rm -r ./dist/img`;
#   `cp -r ./src/client/img ./dist/img`;
# else
#   `mkdir ./dist/img`;
#   `cp -r ./src/client/img ./dist/img`;
# fi
cp ./src/client/img/* ./dist/img/
NODE_ENV='development' PORTS_OFFSET=1 ./node_modules/node-babel/node_modules/babel/bin/babel-node ./src/server/server.js
#node --harmony ./src/server/dev_server.js